name: GitHub Stats Update
on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch:      # Allows you to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anuraghazra/github-readme-stats@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: generated_stats/
          username: rishiraman27
          show_icons: true
          theme: radical
